#格式: 索引 菜单名 url(只是全选也需要占位) 类型(0 不显示菜单,记录日志,1 不显示菜单,不记录日志 ,2 显示菜单,记录日志)
from django.utils.translation import ugettext_lazy as _

from framework.route import reverse_view
from myadmin.models.menu import MenuConfig as _m
from .menu_system import MenuList

MenuList = [
_m('0',_('充值统计')),
	_m('0.1', _('充值流水'), reverse_view('game_manage.pay.pay_result_list'), 0, 1),
		_m('0.1.1', _('直冲_界面'), '/game_manage/pay/add/zhichong', 0, 0),
		_m('0.1.1', _('直冲_确定'), reverse_view('game_manage.pay.do_add'), 0, 0),
		_m('0.1.1', _('补单'), reverse_view('game_manage.pay.pay_fix'), 0, 0),
		_m('0.1.1', _('人工审核'), reverse_view('game_manage.pay.pay_check'), 0, 0),
		_m('0.1.1', _('审核发放'), reverse_view('game_manage.pay.pay_confirm'), 0, 0),
		_m('0.1.1', _('重发订单'), reverse_view('game_manage.pay.pay_reissue'), 0, 0),

_m('3',_('玩家数据查询')),
		_m('3.1', _('玩家角色管理'), reverse_view('game_manage.player.player_list'), 0, 1),
			_m('3.1.1', _('角色信息'), reverse_view('game_manage.game.player.role_info'), 0, 0),

_m('4',_('游戏管理操作')),
	_m('4.1', _('游戏活动列表'), reverse_view('game_manage.game.activity.activity_list'), 0, 1),
		_m('4.1.0', _('游戏活动_编辑'), reverse_view('game_manage.game.activity.activity_edit'), 0, 0),
		_m('4.1.1', _('游戏活动_保存'), reverse_view('game_manage.game.activity.activity_save'), 0, 0),
		_m('4.1.2', _('游戏活动_查询'), reverse_view('game_manage.game.activity.activity_query'), 0, 0),
		_m('4.1.3', _('游戏活动_开启'), reverse_view('game_manage.game.activity.activity_on'), 0, 0),
		_m('4.1.4', _('游戏活动_关闭'), reverse_view('game_manage.game.activity.activity_off'), 0, 0),
		_m('4.1.5', _('游戏活动_活动状态'), reverse_view('game_manage.game.activity.activity_status'), 0, 0),
		_m('4.1.6', _('游戏活动_参数配置'), reverse_view('game_manage.game.activity.activity_setting'), 0, 0),
		_m('4.1.7', _('游戏活动_参数历史'), reverse_view('game_manage.game.activity.activity_setting')+'is_read=true', 0, 0),
		_m('4.1.8', _('游戏活动_模版列表'), '/game_manage/activity_template/list', 0, 0),
		_m('4.1.9', _('游戏活动_模版保存'), '/game_manage/activity_template/save', 0, 0),
		_m('4.1.10', _('游戏活动_模版删除'), '/game_manage/activity_template/remove', 0, 0),
		_m('4.1.11', _('游戏活动_删除'), reverse_view('game_manage.game.activity.activity_remove'), 0, 0),
		_m('4.1.12', _('活动图片上传'), reverse_view('game_manage.game.activity.activity_upload'), 0, 0),
	_m('4.2', _('游戏活动管理'), reverse_view('game_manage.game.activity.activity_manage'), 0, 0),
	_m('4.2', _('活动修改记录'), '/analysis/query/view/活动修改记录', 0, 0),

_m('5',_('运营工具')),
	_m('5.0', _('公告管理'), reverse_view('game_manage.notice.notice_list')),
		_m('5.0.1', _('公告_编辑'), reverse_view('game_manage.notice.notice_edit'), 0, 0),
		_m('5.0.2', _('公告_保存'), reverse_view('game_manage.notice.notice_save'), 0, 0),
		_m('5.0.3', _('公告_删除'), reverse_view('game_manage.notice.notice_remove'), 0, 0),
		_m('5.0.3', _('公告_生成'), reverse_view('game_manage.notice.notice_create_static_file'), 0, 0),
		_m('5.0.3', _('图片_上传'), reverse_view('game_manage.upload.img'), 0, 0),

	_m('5.1',_('游戏服管理'),'/game_manage/server/server_list'),
		_m('5.1.1',_('游戏服_编辑'),'/game_manage/server/server_edit',0,0),
		_m('5.1.2',_('游戏服_删除'),'/game_manage/server/server_remove',0, 0),
		_m('5.1.3',_('游戏服_保存'),'/game_manage/server/server_save',0, 0),
		_m('5.1.4',_('服务器参数'),'/game_manage/game/server/server_info',0, 0),
		_m('5.1.5',_('滚动公告'),'/game_manage/game/server/roll_broadcast',0, 0),
		_m('5.1.6',_('同步表'),'/game_manage/log/log_syncdb',0, 0),
		_m('5.1.7',_('修改服务器状态'),'/game_manage/server/server_status_edit?action=change_status',0, 0),
		_m('5.1.7',_('修改版本号'),'/game_manage/server/server_status_edit?action=change_version',0, 0),
		_m('5.1.8',_('聊天公告'),'/game_manage/game/send',0, 0),
		_m('5.1.9',_('生成服务器列表'),reverse_view('game_manage.server.server_make'),0, 0),
		_m('5.1.10',_('显示服务器信息'),reverse_view('game_manage.server.server_msg'),0, 0),
	_m('5.2',_('服分区管理'),reverse_view('game_manage.group.group_list')),
		_m('5.2.1',_('分区_编辑'),reverse_view('game_manage.group.group_edit'),0, 0),
		_m('5.2.2',_('分区_保存'),reverse_view('game_manage.group.group_save'),0, 0),
		_m('5.2.3',_('分区_删除'),reverse_view('game_manage.group.group_remove'),0, 0),
		_m('5.2.3',_('分组_编辑'),reverse_view('game_manage.group.grouplist_edit'),0, 0),
		_m('5.2.3',_('分组_删除'),reverse_view('game_manage.group.grouplist_remove'),0, 0),
		_m('5.2.3',_('分组_保存'),reverse_view('game_manage.group.grouplist_save'),0, 0),
	_m('5.3', _('渠道管理'), reverse_view('game_manage.channel.channel_list')),
		_m('5.3.1', _('渠道_编辑'), reverse_view('game_manage.channel.channel_edit'), 0, 0),
		_m('5.3.2', _('渠道_保存'), reverse_view('game_manage.channel.channel_save'), 0, 0),
		_m('5.3.3', _('渠道_删除'), reverse_view('game_manage.channel.channel_remove'), 0, 0),
		_m('5.3.3', _('平台_编辑'), reverse_view('game_manage.channel.agent_edit'), 0, 0),
		_m('5.3.3', _('平台_保存'), reverse_view('game_manage.channel.agent_save'), 0, 0),
		_m('5.3.3', _('平台_删除'), reverse_view('game_manage.channel.agent_remove'), 0, 0),
		_m('5.3.3', _('渠道信息_生成'), reverse_view('game_manage.channel.channel_make'), 0, 0),
	_m('5.4', _('版本更新管理'), reverse_view('game_manage.upgrade.upgrade_list')),
		_m('5.4.1', _('更新_编辑'), reverse_view('game_manage.upgrade.upgrade_edit'), 0, 0),
		_m('5.4.2', _('更新_保存'), reverse_view('game_manage.upgrade.upgrade_save'), 0, 0),
		_m('5.4.3', _('更新_删除'), reverse_view('game_manage.upgrade.upgrade_remove'), 0, 0),
		_m('5.4.3', _('更新_生成更新json文件'), reverse_view('game_manage.upgrade.upgrade_make'), 0, 0),
		_m('5.4.3', _('更新_清除旧文件'), reverse_view('game_manage.upgrade.upgrade_clear'), 0, 0),
	_m('5.5', _('登录账号管理'), reverse_view('game_manage.user.user_list')),
		_m('5.5.1', _('封号'), reverse_view('game_manage.user.user_lock'), 0, 0),
		_m('5.5.2', _('解封'), reverse_view('game_manage.user.user_unlock'), 0, 0),
		_m('5.5.3', _('改密码'), reverse_view('game_manage.user.user_password'), 0, 0),
		_m('5.5.4', _('清密保'), reverse_view('game_manage.user.clear_mibao'), 0, 0),
		_m('5.5.5', _('改密保'), reverse_view('game_manage.user.user_password'), 0, 0),
		_m('5.5.6', _('修改帐号状态'), reverse_view('game_manage.user.user_status_edit'), 0, 0),
	_m('5.6', _('日历&事件'), reverse_view('game_manage.calevents.calendar_list')),

	_m('5.7', _('礼包卡管理'), reverse_view('game_card.card.batch.batch_list')),
        _m('5.7.0', _('礼包卡记录_列表'), reverse_view('game_card.card.card_log_list'), 0, 0),
		_m('5.7.1', _('礼包卡_编辑'), reverse_view('game_card.card.batch.batch_edit'), 0, 0),
		_m('5.7.2', _('礼包卡_保存'), reverse_view('game_card.card.batch.batch_save'), 0, 0),
		_m('5.7.3', _('礼包卡_删除'), reverse_view('game_card.card.batch.batch_del'), 0, 0),
		_m('5.7.3', _('礼包卡_生成'), reverse_view('game_card.card.card_create'), 0, 0),
		_m('5.7.3', _('礼包卡_导出'), reverse_view('game_card.card.export_card'), 0, 0),


	_m('5.10', _('推送管理'), reverse_view('game_manage.notice.notice_list')+'?notice_type=4'),
		_m('5.10.1', _('生成推送消息'), reverse_view('game_manage.notice.push_create'), 0, 0),
		_m('5.10.2', _('添加'), reverse_view('game_manage.notice.notice_edit')+'?notice_type=4', 0, 0),
		_m('5.10.3', _('保存'), reverse_view('game_manage.notice.notice_save'), 0, 0),

	_m('5.11', _('用户类型管理'), reverse_view('game_manage.user_type.user_type_list')),
		_m('5.11.0', _('用户类型_编辑'), reverse_view('game_manage.user_type.user_type_edit'), 0, 0),
		_m('5.11.1', _('用户类型_保存'), reverse_view('game_manage.user_type.user_type_save'), 0, 0),
		_m('5.11.2', _('用户类型_删除'), reverse_view('game_manage.user_type.user_type_del'), 0, 0),

	_m('5.12', _('充值通道管理'), reverse_view('game_manage.pay.pay_channel_list')),
		_m('5.12.0', _('充值通道_编辑'), reverse_view('game_manage.pay.pay_channel_edit'), 0, 0),
		_m('5.12.1', _('充值通道_保存'), reverse_view('game_manage.pay.pay_channel_save'), 0, 0),
		_m('5.12.2', _('充值通道_删除'), reverse_view('game_manage.pay.pay_channel_remove'), 0, 0),


	_m('5.13',_('客服')),
		_m('5.13.1', _('问题列表'), reverse_view('game_manage.question.manage_question_list')),
			_m('5.13.1.1', _('问题回复'), reverse_view('game_manage.question.manage_question_answer'), 0, 0),
			_m('5.13.1.1', _('编辑问题分类'), '/log_def/dict_define/edit/?key=question_category', 0, 0),
			_m('5.13.1.1', _('保存问题分类'), '/log_def/dict_define/save/?key=question_category', 0, 0),
]+MenuList
