# Generated by Django 2.0.13 on 2021-02-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flink_platform', '0002_auto_20210225_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeparagraph',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flink_platform.Project', verbose_name='所属项目'),
        ),
    ]
