# Generated by Django 3.0.13 on 2021-03-31 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flink_platform', '0004_auto_20210317_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flinkjob',
            name='flink_config',
            field=models.TextField(blank=True, default='#全局任务 https://ci.apache.org/projects/flink/flink-docs-release-1.12/zh/deployment/config.html\nrestart-strategy fixed-delay\nrestart-strategy.fixed-delay.attempts 3\nrestart-strategy.fixed-delay.delay 20s\nstate.checkpoints.num-retained 3 \nexecution.checkpointing.tolerable-failed-checkpoints 3\n# 设置任务使用的时间属性是eventtime\npipeline.time-characteristic EventTime\n# 设置checkpoint的时间间隔\nexecution.checkpointing.interval 5min\n# 确保检查点之间的间隔\nexecution.checkpointing.min-pause 1min\n# 设置checkpoint的超时时间\nexecution.checkpointing.timeout 10min\n# 设置任务取消后保留hdfs上的checkpoint文件\nexecution.checkpointing.externalized-checkpoint-retention RETAIN_ON_CANCELLATION\nexecution.savepoint.ignore-unclaimed-state true\n#taskmanager.memory.process.size 1024mb\n\n    ', null=True, verbose_name='flink config 配置'),
        ),
        migrations.AlterField(
            model_name='flinkjobgroup',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
